README.md

Signed-off-by: Rob Dolin <robdolin@microsoft.com>

[ReadMe] Add example to Apply | intended program

---

MAINTAINERS
README.md

closes #23 
Signed-off-by: Jesse Butler <jesse.butler@oracle.com>

remove self from maintainers, project membership

---

README.md

Signed-off-by: David Lyle <david.lyle@intel.com>

update Intel representation

---

README.md

Signed-off-by: Rob Dolin <robdolin@microsoft.com>

Add runc to list of trademarks

---

.gitignore
README-WG.md
README.md
faq.md
instructions.md
participation-form/Certified_OCI_Form.md
reviewing.md
terms-conditions/Certified_OCI_Terms.md

- Fork [cncf/k8s-conformance](https://github.com/cncf/k8s-conformance), maintaining commit history
- Replace references of Kubernetes/k8s/CNCF with OCI
- Remove files and sections that do not apply to OCI
- Expand wording to include multiple OCI specs and versions
- Add TODOs wherever necessary

 Initial submission of cncf/k8s-conformance fork

---

.github/workflows/acr_1.yml
.github/workflows/acr_2.yml
.github/workflows/acr_3.yml
.github/workflows/acr_4.yml

Use different namespaces for ACR tests

---

.github/config/zot-config.yml
.github/workflows/zot_1.yml
.github/workflows/zot_2.yml
.github/workflows/zot_3.yml
.github/workflows/zot_4.yml

Build zot image from tip of zot master

---

.github/config/distribution.yml
.github/workflows/distribution_1.yml
.github/workflows/distribution_2.yml
.github/workflows/distribution_3.yml
.github/workflows/distribution_4.yml
.github/workflows/zot_1.yml

Build docker image from source instead of pulling pre-built image.
@caniszczyk

Update docker/distribution workflow

---

.github/workflows/trow_1.yml
.github/workflows/trow_2.yml
.github/workflows/trow_3.yml
.github/workflows/trow_4.yml

Build image from master instead of using pre-built image.

Update github action for Trow

---

.github/workflows/zot_1.yml
.github/workflows/zot_2.yml
.github/workflows/zot_3.yml
.github/workflows/zot_4.yml

Signed-off-by: Ramkumar Chinchani <rchincha@cisco.com>

zot: fix conformance workflows

---

.github/workflows/zot_1.yml
.github/workflows/zot_2.yml
.github/workflows/zot_3.yml
.github/workflows/zot_4.yml

Signed-off-by: Ramkumar Chinchani <rchincha@cisco.com>

zot: opencontainers/dist-spec has a "main" not "master"

---

.github/config/zot-config.yml
.github/workflows/zot_1.yml
.github/workflows/zot_2.yml
.github/workflows/zot_3.yml
.github/workflows/zot_4.yml

```
CONTAINER ID   IMAGE                       COMMAND                  CREATED         STATUS         PORTS                    NAMES
6645f6246fe3   local-zot:v20210610213618   "/zot serve /etc/zot…"   7 minutes ago   Up 7 minutes   0.0.0.0:5000->5000/tcp   gifted_diffie
...
Ran 49 of 62 Specs in 0.130 seconds
SUCCESS! -- 49 Passed | 0 Failed | 0 Pending | 13 Skipped
PASS

zot: build a self-contained docker image for conformance

---

distribution-spec/README.md

Branding and git repo changest to reflect docker donation of distribution to cncf
Signed-off-by: Steve Lasker <stevenlasker@hotmail.com>

Update docker/distribution to reflect donation to cncf

---

distribution-spec/live/.gitkeep
distribution-spec/live/bundle-bar/badges.md
distribution-spec/v1.0/.gitkeep
distribution-spec/v1.0/bundle-bar/PRODUCT.yaml
distribution-spec/v1.0/bundle-bar/README.md
distribution-spec/v1.0/bundle-bar/junit.xml
distribution-spec/v1.0/bundle-bar/report.html

Also, removing various `.gitkeep` files

Conformance results for distribution-spec/v1.0/bundle-bar

---

distribution-spec/live/badges.md
distribution-spec/live/openregistry/badges.md
distribution-spec/v1.0/openregistry/PRODUCT.yaml
distribution-spec/v1.0/openregistry/README.md
distribution-spec/v1.0/openregistry/junit.xml
distribution-spec/v1.0/openregistry/report.html

- This is the first PR from OpenRegistry to apply for OCI-distribution spec certification
Signed-off-by: guacamole <gunjanwalecha@gmail.com>

Conformance results for distribution-spec/v1.0/openregistry

---

distribution-spec/live/django-oci/badges.md
distribution-spec/v1.0/django-oci/PRODUCT.yaml
distribution-spec/v1.0/django-oci/README.md
distribution-spec/v1.0/django-oci/junit.xml
distribution-spec/v1.0/django-oci/report.html

So excited for this! 
https://opencontainers.org/posts/blog/2021-11-30-oci-conformance/
Here are the results for Django OCI. if y'all aren't familiar with Django, it's a popular Python framework that has a really nice module/plugin system, so django-oci is implemented as such. A made this a little while back hoping to bring in more academics to the OCI community!
Signed-off-by: vsoch <vsoch@users.noreply.github.com>

Adding conformance results for django oci!

---

distribution-spec/live/azurecontainerregistry/badges.md
distribution-spec/v1.0/azurecontainerregistry/PRODUCT.yaml
distribution-spec/v1.0/azurecontainerregistry/README.md
distribution-spec/v1.0/azurecontainerregistry/junit.xml
distribution-spec/v1.0/azurecontainerregistry/report.html

This PR adds the conformance results for Azure Container Registry
Signed-off-by: gildardogmsft gildardog@microsoft.com

Add Azure Container Registry conformance tests

---

netlify.toml

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

debugging netlify

---

products-page-generator/index.md.tpl

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>

docs: fix typo in the TOC

---

distribution-spec/live/gitlab/badges.md
distribution-spec/v1.0/gitlab/PRODUCT.yaml
distribution-spec/v1.0/gitlab/README.md
distribution-spec/v1.0/gitlab/junit.xml
distribution-spec/v1.0/gitlab/report.html

Adds Distribution Spec conformance test results for the GitLab Container Registry.

Conformance results for distribution-spec/v1.0/gitlab

---

products-page-generator/index.md.tpl

fix: generate proper anchor link for toc

---

MAINTAINERS

This was discussed during one of oci the call and after checking with @shizhMSFT decided to open this PR. There were some challenges on the distribution and if there are similar concerns on this repo then I can close this PR but would like to hear from other maintainers if there are concerns.

Add Shiwei as maintainer

---

Dockerfile
README.md
hack/build-static-site.sh
products-page-generator/index.md.tpl

A follow up to #112 
Resolves #117 
Resolves #118

Site maintenance etc. pt 2

---

distribution-spec/v1.0/gitea/PRODUCT.yaml
distribution-spec/v1.0/gitea/README.md
distribution-spec/v1.0/gitea/junit.xml
distribution-spec/v1.0/gitea/report.html

Adds Distribution Spec v1.0 Conformance Test Results for the Gitea Container Registry.

Conformance results for distribution-spec/v1.0/gitea
